import Head from "next/head";
import Banner from "../components/Banner";
import Experience from "../components/Experience";
import ShowCase from "../components/Showcase";
import Layout from "../layout/Layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Niaz Morshed's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Banner />
        <Experience />
        <ShowCase />
      </Layout>
    </div>
  );
}
